import { jsx as _jsx, Fragment as _Fragment, jsxs as _jsxs } from "react/jsx-runtime";
import { createRoot } from "react-dom/client";
import { GlobalStyles } from "./ui/globalStyles";
import { store } from "./store";
import { Provider } from "react-redux";
import "react-toastify/dist/ReactToastify.css";
import { MovieHub } from "./MovieHub";
// import { Toast } from "components";
const root = createRoot(document.getElementById("root"));
root.render(_jsxs(_Fragment, { children: [_jsx(GlobalStyles, {}), _jsx(Provider, { store: store, children: _jsx(MovieHub, {}) })] }));
